# Generated by Django 3.0.6 on 2020-05-11 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_nodeview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='example_nodeview.Person'),
        ),
    ]
