# Generated by Django 3.0.6 on 2020-05-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_nodeview', '0002_auto_20200511_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='houses',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', to='example_nodeview.House'),
        ),
        migrations.AlterField(
            model_name='person',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='example_nodeview.Person'),
        ),
    ]
